name: Bug Report
description: Report a bug
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened?
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: NXC command and relevant output
      render: bash

  - type: input
    id: version
    attributes:
      label: Module version
      placeholder: v0.1.0

  - type: input
    id: target-os
    attributes:
      label: Target OS
      placeholder: Windows Server 2019
